-- Deploy wildcamp:init to pg
BEGIN;

-- XXX Add DDLs here.
CREATE TABLE "user" (
  id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  email TEXT NOT NULL UNIQUE,
  "password" TEXT NOT NULL,
  username TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  modified_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE campground (
  id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL UNIQUE,
  "image" TEXT NOT NULL,
  "description" TEXT NOT NULL,
  country TEXT NOT NULL,
  "user_id" INT NOT NULL REFERENCES "user"(id) ON DELETE CASCADE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  modified_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE comment (
  id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  "text" TEXT NOT NULL UNIQUE,
  campground_id INT NOT NULL REFERENCES "campground"(id) ON DELETE CASCADE,
  "user_id" INT NOT NULL REFERENCES "user"(id) ON DELETE CASCADE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  modified_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

COMMIT;